language: node_js
node_js:
- '6.9'
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
before_deploy: "npm run build"
deploy:
  provider: npm
  email: apiteam@swagger.io
  skip_cleanup: true
  api_key:
    secure: "IJkLaACa+rfERf1O5nwlqOyuo9sbul3FBhBt4Un9P+DvEet3AoDPV9NQVLd8SkmQYKGbGQWF4BIdjrO5nqFD6Te+JTeUX5Uo/DFS/fu9qw1xv0dQpvbJFuoYnnFlbzGTEs4CFa8lbu3ZromFHQGOQxRobjsG1Kf0dWFSSzmND3g="
  on:
    tags: true
    repo: swagger-api/swagger-ui
    node: '6.9'
