# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CYPRESS_CACHE_FOLDER: cypress/cache

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Cypress binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: |
          steps.cache-node-modules.outputs.cache-hit != 'true' ||
          steps.cache-cypress-binary.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code for errors only
        run: npm run lint-errors
      - name: Run all tests
        run: npm run just-test-in-node && npm run test:unit-jest
        env:
          CI: true
      - name: Build SwaggerUI
        run: npm run build
      - name: Test build artifacts
        run: npm run test:artifact

  e2e-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.5.0-chrome94-ff93
    strategy:
      fail-fast: false
      matrix:
        containers: [bugs, 'features/**/[a-o]', 'features/**/[p-z]', "{a11y,security}"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Cache Cypress binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: |
          steps.cache-node-modules.outputs.cache-hit != 'true' ||
          steps.cache-cypress-binary.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cypress Test
        uses: cypress-io/github-action@v2
        with:
          spec: test/e2e-cypress/tests/${{ matrix.containers }}/**/*.js
          browser: chrome
          start: npm run hot-e2e-cypress-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

